#!/usr/bin/env bash

set -e

echo "Installing ansible..."
if ! [ -x "$(command -v ansible)" ]; then
    # Installs ansible
    sudo -E apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367
    sudo apt-get update -y
    sudo apt-get install curl git software-properties-common ansible-core -y
fi

TIMESTAMP=`date +%Y-%m-%d.%H:%M:%S`

echo "Creating backup of current configuration..."
[ ! -f ~/.config/gitignore ] || mv ~/.config/gitignore ~/.config/gitignore.bak.${TIMESTAMP}
[ ! -d ~/.config/nvim ] || mv ~/.config/nvim ~/.config/nvim.bak.${TIMESTAMP}
[ ! -f ~/.config/terminator/config ] || mv ~/.config/terminator/config  ~/.config/terminator/config.bak.${TIMESTAMP}
[ ! -f ~/.gitconfig ] || mv ~/.gitconfig ~/.gitconfig.bak.${TIMESTAMP}
[ ! -f ~/.inputrc ] || mv ~/.inputrc ~/.inputrc.bak.${TIMESTAMP}
[ ! -d ~/.oh-my-zsh ] || mv ~/.oh-my-zsh ~/.oh-my-zsh.bak.${TIMESTAMP}
[ ! -f ~/.p10k.zsh ] || mv ~/.p10k.zsh ~/.p10k.zsh.bak.${TIMESTAMP}
[ ! -d ~/.tmux ] || mv ~/.tmux ~/.tmux.bak.${TIMESTAMP}
[ ! -f ~/.tmux.conf ] || mv ~/.tmux.conf ~/.tmux.conf.bak.${TIMESTAMP}
[ ! -f ~/.zshrc ] || mv ~/.zshrc ~/.zshrc.bak.${TIMESTAMP}

# Project root directory
ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Host file location
HOSTS="$ROOTDIR/hosts"
# Main playbook
PLAYBOOK="$ROOTDIR/local.yml"

# Runs Ansible playbook using user.
echo "Running Ansible playbook..."
ansible-playbook -i "$HOSTS" "$PLAYBOOK" --ask-become-pass

if command -v terminal-notifier 1>/dev/null 2>&1; then
    terminal-notifier -title "Ansible: Bootstrap complete" -message "Successfully set up dev environment."
fi

exit 0
