---
- name: Check debug adapter exists
  stat:
    path: "/usr/local/bin/OpenDebugAD7"
  register: c
  tags:
    - cpp
- name: Download vscode-cpptools
  become: true
  become_user: "{{ main_user }}"
  get_url:
    url:
      "https://github.com/microsoft/vscode-cpptools/releases/download/1.7.1/cpptools-linux.vsix"
    dest: "{{ main_user_dir }}"
  when: not c.stat.exists
  tags:
    - cpp
- name: Create cpptools directory
  become: true
  become_user: "{{ main_user }}"
  file:
    path: "{{ main_user_dir }}/.cpptools/cpptools-linux"
    state: directory
    mode: 0755
  when: not c.stat.exists
  tags:
    - cpp
- name: Extract cpptools
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.unarchive:
    src: "{{ main_user_dir }}/cpptools-linux.vsix"
    dest: "{{ main_user_dir }}/.cpptools/cpptools-linux"
  when: not c.stat.exists
  tags:
    - cpp
- name: Make cpptools an executable
  become: true
  file:
    src: "{{ main_user_dir }}/.cpptools/cpptools-linux/extension/debugAdapters/bin/OpenDebugAD7"
    dest: "/usr/local/bin/OpenDebugAD7"
    mode: a+x
    state: link
  when: not c.stat.exists
  tags:
    - cpp
- name: Check debug adapter config exists
  stat:
    path: "{{ main_user_dir }}/.cpptools/cpptools-linux/extension/debugAdapters/bin/nvim-dap.ad7Engine.json"
  register: d
  tags:
    - cpp
- name: Create copy of json config
  become: true
  become_user: "{{ main_user }}"
  file:
    src: "{{ main_user_dir }}/.cpptools/cpptools-linux/extension/debugAdapters/bin/cppdbg.ad7Engine.json"
    dest: "{{ main_user_dir }}/.cpptools/cpptools-linux/extension/debugAdapters/bin/nvim-dap.ad7Engine.json"
    state: hard
    mode: 0644
  when: not d.stat.exists
  tags:
    - cpp
- name: Cleanup
  become: true
  ansible.builtin.file:
    path: "{{ main_user_dir }}/cpptools-linux.vsix"
    state: absent
  when: not c.stat.exists
  tags:
    - cpp
