---
- name: Clone Neovim
  become: true
  become_user: "{{ main_user }}"
  retries: 3
  delay: 10
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ main_user_dir }}/neovim"
    version: nightly
  tags:
    - neovim
- name: Install build requirements for neovim
  become: true
  apt:
    pkg:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    update_cache: true
  tags:
    - nvim
- name: Neovim Plugin Development 1
  apt: name=luarocks
  become: true
  tags:
    - neovim
- name: Neovim Plugin Development 2 luacheck
  ansible.builtin.command: luarocks install luacheck
  register: luacheck_install
  changed_when: luacheck_install.rc != 0
  failed_when: luacheck_install.rc != 0
  retries: 3
  delay: 10
  ignore_errors: true
  tags:
    - neovim
- name: Build neovim
  become: true
  become_user: "{{ main_user }}"
  ansible.builtin.make:
    chdir: "{{ main_user_dir }}/neovim"
    params:
      CMAKE_BUILD_TYPE=RelWithDebInfo
  register: build_neovim
  tags:
    - neovim
- name: Install neovim
  become: true
  command: make install
  args:
    chdir: "{{ main_user_dir }}/neovim"
  register: install_neovim
  changed_when: install_neovim.rc != 0
  failed_when: install_neovim.rc != 0
  tags:
    - neovim
